import { DocumentTemplate, PreviewData, PreviewSection } from './types';

export const DefaultTemplate: DocumentTemplate = {
    id: 'default',
    name: 'Standard',
    css: `
        .template-container.default {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            background-color: #ffffff;
            max-width: 8.5in;
            margin: 0 auto;
            padding: 40px;
        }

        .default h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 0.5rem; color: #111; }
        .default h2 { font-size: 1.5rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; border-bottom: 2px solid #eee; padding-bottom: 0.5rem; }
        .default p { margin-bottom: 1rem; font-size: 1.1rem; }
        .default ul { margin-bottom: 1.5rem; padding-left: 1.5rem; }
        .default li { margin-bottom: 0.5rem; }
        
        .default .header { margin-bottom: 3rem; }
        .default .metadata { font-size: 0.9rem; color: #666; display: flex; gap: 2rem; margin-top: 1rem; }
        
        .default .block { 
            margin: 1.5rem 0;
            padding: 1.5rem;
            border-radius: 12px;
            background: #f8f9fa;
            border: 1px solid #e9ecef;
        }
        
        .default .block-title {
            font-weight: 700;
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            color: #666;
            margin-bottom: 0.75rem;
            display: block;
        }

        @media print {
            .template-container.default { padding: 0; }
        }
    `,
    render: (data: PreviewData) => {
        const renderSection = (section: PreviewSection) => {
            const { type, heading, content } = section;

            if (type === 'heading') return `<h2>${content}</h2>`;
            if (type === 'paragraph') return `<p>${content}</p>`;
            if (type === 'list') {
                if (Array.isArray(content)) {
                    return `<ul>${content.map(c => `<li>${c}</li>`).join('')}</ul>`;
                }
                return `<li>${content}</li>`;
            }

            return `
                <div class="block">
                    ${heading ? `<span class="block-title">${heading}</span>` : ''}
                    <div class="block-content">
                        ${Array.isArray(content) ? `<ul>${content.map(c => `<li>${typeof c === 'string' ? c : JSON.stringify(c)}</li>`).join('')}</ul>` : content}
                    </div>
                </div>
            `;
        };

        return `
            <div class="template-container default">
                <header class="header">
                    <h1>${data.title || 'Untitled Document'}</h1>
                    <div class="metadata">
                        ${data.metadata.wordCount ? `<span>Words: ${data.metadata.wordCount}</span>` : ''}
                        <span>Date: ${new Date().toLocaleDateString()}</span>
                    </div>
                </header>

                <main class="content">
                    ${data.sections.map(section => renderSection(section)).join('')}
                </main>

                <footer style="margin-top: 4rem; padding-top: 2rem; border-top: 1px solid #eee; font-size: 0.8rem; color: #999; text-align: center;">
                    Generated by PDFy
                </footer>
            </div>
        `;
    }
};
