import { DocumentTemplate } from './types';
import { PreviewData } from '../utils/contentTransformer';

export const ProfessionalTemplate: DocumentTemplate = {
    id: 'professional',
    name: 'Professional',
    css: `
        .template-container.professional {
            font-family: 'Inter', 'Segoe UI', Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            background-color: #ffffff;
            max-width: 850px;
            margin: 0 auto;
            padding: 60px 50px;
        }
        .professional h1 { 
            font-size: 32px; 
            margin-bottom: 8px; 
            color: #0f172a; 
            font-weight: 800;
            letter-spacing: -0.025em;
        }
        .professional .metadata {
            display: flex;
            gap: 16px;
            font-size: 14px;
            color: #64748b;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 1px solid #e2e8f0;
        }
        .professional .section {
            margin-bottom: 32px;
        }
        .professional h2 { 
            font-size: 22px; 
            margin-top: 0;
            margin-bottom: 16px; 
            color: #1e293b; 
            font-weight: 700;
            border-left: 4px solid #0f172a;
            padding-left: 16px;
        }
        .professional p { 
            margin: 0 0 16px 0; 
            color: #334155;
        }
        .professional ul {
            margin: 0 0 16px 0;
            padding-left: 24px;
        }
        .professional li {
            margin-bottom: 8px;
            color: #334155;
        }
        .professional .footer {
            margin-top: 60px;
            padding-top: 24px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 12px;
            color: #94a3b8;
        }
    `,
    render: (data: PreviewData) => {
        return `
            <div class="template-container professional">
                <h1>${data.title}</h1>
                
                <div class="metadata">
                    ${data.metadata.wordCount ? `<span>${data.metadata.wordCount} words</span>` : ''}
                    ${data.metadata.readTime ? `<span>• ${data.metadata.readTime} min read</span>` : ''}
                    ${data.metadata.totalQuestions ? `<span>• ${data.metadata.totalQuestions} questions</span>` : ''}
                    ${data.metadata.totalCards ? `<span>• ${data.metadata.totalCards} cards</span>` : ''}
                </div>

                <div class="sections">
                    ${data.sections.map(section => `
                        <div class="section">
                            ${section.heading ? `<h2>${section.heading}</h2>` : ''}
                            <div class="content">
                                ${section.type === 'list'
                ? `<ul>${section.content.split('\n').filter(Boolean).map(item => `<li>${item}</li>`).join('')}</ul>`
                : `<div class="formatted-content">${section.content}</div>`
            }
                            </div>
                        </div>
                    `).join('')}
                </div>

                <div class="footer">
                    Generated by PDFy • ${new Date().toLocaleDateString()}
                </div>
            </div>
        `;
    }
};
