import { DocumentTemplate } from './types';
import { PreviewData } from '../utils/contentTransformer';

export const StudyTemplate: DocumentTemplate = {
    id: 'study',
    name: 'Study Note',
    css: `
        .template-container.study {
            font-family: 'Times New Roman', Times, serif;
            line-height: 1.6;
            color: #1a1a1a;
            background-color: #ffffff;
            max-width: 850px;
            margin: 0 auto;
            padding: 40px;
        }
        .study h1 { 
            font-size: 24pt; 
            margin-bottom: 20px; 
            color: #000; 
            font-weight: bold;
            text-align: center;
            text-transform: uppercase;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .study .metadata {
            text-align: center;
            font-size: 10pt;
            color: #666;
            margin-bottom: 40px;
            font-style: italic;
        }
        .study .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .study h2 { 
            font-size: 16pt; 
            margin-top: 0;
            margin-bottom: 15px; 
            color: #111; 
            font-weight: bold;
            border-bottom: 1px solid #666;
            padding-bottom: 5px;
            text-transform: uppercase;
        }
        .study p { 
            margin: 0 0 15px 0; 
            text-align: justify;
        }
        .study ul, .study ol {
            margin: 0 0 20px 0;
            padding-left: 40px;
        }
        .study li {
            margin-bottom: 8px;
        }
        .study .footer {
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #ccc;
            text-align: center;
            font-size: 9pt;
            color: #666;
        }
    `,
    render: (data: PreviewData) => {
        return `
            <div class="template-container study">
                <h1>${data.title}</h1>
                
                <div class="metadata">
                    ${data.metadata.wordCount ? `<span>${data.metadata.wordCount} words</span>` : ''}
                    ${data.metadata.readTime ? `<span> • ${data.metadata.readTime} minute read</span>` : ''}
                    <span> • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
                </div>

                <div class="sections">
                    ${data.sections.map(section => `
                        <div class="section">
                            ${section.heading ? `<h2>${section.heading}</h2>` : ''}
                            <div class="content">
                                ${section.type === 'list'
                ? `<ul>${section.content.split('\n').filter(Boolean).map(item => `<li>${item}</li>`).join('')}</ul>`
                : `<p>${section.content}</p>`
            }
                            </div>
                        </div>
                    `).join('')}
                </div>

                <div class="footer">
                    Study Material Generated by pdfx • ${new Date().getFullYear()}
                </div>
            </div>
        `;
    }
};
