'use client';
const _jsxFileName = "j:\\antigravity\\pdfx\\src\\components\\DocumentPreview\\presets\\Presets.tsx";import React from 'react';

import '../animations.css';





/**
 * Professional Preset
 * Clean, corporate styling with Inter font
 */
export const ProfessionalPreset = ({ data }) => {
    return (
        React.createElement('div', { className: "max-w-[800px] mx-auto px-8 py-12 bg-white text-black font-sans"      , __self: this, __source: {fileName: _jsxFileName, lineNumber: 15}}
            /* Title */
            , React.createElement('h1', { className: "text-4xl font-bold mb-2 text-gray-900"   , style: { fontFamily: 'Inter, sans-serif' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 17}}
                , data.title
            )

            /* Metadata */
            , data.metadata && (
                React.createElement('div', { className: "flex gap-4 text-sm text-gray-500 mb-8 pb-4 border-b border-gray-200"       , __self: this, __source: {fileName: _jsxFileName, lineNumber: 23}}
                    , data.metadata.wordCount && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 24}}, data.metadata.wordCount, " words" )
                    , data.metadata.readTime && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 25}}, "• " , data.metadata.readTime, " min read"  )
                    , data.metadata.count && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 26}}, "• " , data.metadata.count, " items" )
                    , data.metadata.totalQuestions && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 27}}, "• " , data.metadata.totalQuestions, " questions" )
                    , data.metadata.totalCards && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 28}}, "• " , data.metadata.totalCards, " cards" )
                )
            )

            /* Content Sections */
            , React.createElement('div', { className: "space-y-8", __self: this, __source: {fileName: _jsxFileName, lineNumber: 33}}
                , data.sections.map((section, index) => (
                    React.createElement('div', { key: index, className: "preview-section", __self: this, __source: {fileName: _jsxFileName, lineNumber: 35}}
                        , section.heading && (
                            React.createElement('h2', { className: "text-2xl font-semibold mb-4 text-gray-800"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 37}}
                                , section.heading
                            )
                        )
                        , React.createElement('div', {
                            className: "text-base leading-relaxed text-gray-700"  ,
                            style: { lineHeight: '1.75' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 41}}

                            , section.type === 'list' ? (
                                React.createElement('ul', { className: "list-disc pl-6 space-y-2"  , __self: this, __source: {fileName: _jsxFileName, lineNumber: 46}}
                                    , section.content.split('\n').filter(Boolean).map((item, i) => (
                                        React.createElement('li', { key: i, __self: this, __source: {fileName: _jsxFileName, lineNumber: 48}}, item)
                                    ))
                                )
                            ) : (
                                React.createElement('p', { className: "whitespace-pre-wrap", __self: this, __source: {fileName: _jsxFileName, lineNumber: 52}}, section.content)
                            )
                        )
                    )
                ))
            )

            /* Footer */
            , React.createElement('div', { className: "mt-12 pt-6 border-t border-gray-200 text-sm text-gray-400 text-center"      , __self: this, __source: {fileName: _jsxFileName, lineNumber: 60}}, "Generated by PDFy • "
                    , new Date().toLocaleDateString()
            )
        )
    );
};

/**
 * Academic Preset
 * Serif font, formal styling, two-column layout for content
 */
export const AcademicPreset = ({ data }) => {
    return (
        React.createElement('div', { className: "max-w-[900px] mx-auto px-12 py-16 bg-white text-black"     , style: { fontFamily: 'Georgia, serif' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 73}}
            /* Title */
            , React.createElement('h1', { className: "text-5xl font-bold mb-3 text-center text-gray-900"    , __self: this, __source: {fileName: _jsxFileName, lineNumber: 75}}
                , data.title
            )

            /* Metadata */
            , data.metadata && (
                React.createElement('div', { className: "text-center text-sm text-gray-600 mb-12 pb-6 border-b-2 border-gray-300"      , __self: this, __source: {fileName: _jsxFileName, lineNumber: 81}}
                    , data.metadata.wordCount && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 82}}, data.metadata.wordCount, " words" )
                    , data.metadata.readTime && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 83}}, " • "  , data.metadata.readTime, " minute read"  )
                    , data.metadata.totalQuestions && React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 84}}, " • "  , data.metadata.totalQuestions, " questions" )
                )
            )

            /* Content Sections */
            , React.createElement('div', { className: "space-y-12", __self: this, __source: {fileName: _jsxFileName, lineNumber: 89}}
                , data.sections.map((section, index) => (
                    React.createElement('div', { key: index, className: "preview-section", __self: this, __source: {fileName: _jsxFileName, lineNumber: 91}}
                        , section.heading && (
                            React.createElement('h2', { className: "text-3xl font-semibold mb-6 text-gray-800 border-b border-gray-300 pb-2"      , __self: this, __source: {fileName: _jsxFileName, lineNumber: 93}}
                                , section.heading
                            )
                        )
                        , React.createElement('div', {
                            className: "text-lg leading-loose text-gray-800"  ,
                            style: { lineHeight: '2.0', textAlign: 'justify' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 97}}

                            , section.type === 'list' ? (
                                React.createElement('ul', { className: "list-decimal pl-8 space-y-3"  , __self: this, __source: {fileName: _jsxFileName, lineNumber: 102}}
                                    , section.content.split('\n').filter(Boolean).map((item, i) => (
                                        React.createElement('li', { key: i, className: "pl-2", __self: this, __source: {fileName: _jsxFileName, lineNumber: 104}}, item)
                                    ))
                                )
                            ) : (
                                React.createElement('p', { className: "whitespace-pre-wrap indent-8" , __self: this, __source: {fileName: _jsxFileName, lineNumber: 108}}, section.content)
                            )
                        )
                    )
                ))
            )

            /* Footer */
            , React.createElement('div', { className: "mt-16 pt-8 border-t-2 border-gray-300 text-center text-sm text-gray-500"      , __self: this, __source: {fileName: _jsxFileName, lineNumber: 116}}
                , React.createElement('p', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 117}}, "Generated: " , new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))
            )
        )
    );
};

/**
 * Minimal Preset
 * Ultra-clean, system fonts, narrow column
 */
export const MinimalPreset = ({ data }) => {
    return (
        React.createElement('div', { className: "max-w-[600px] mx-auto px-6 py-10 bg-white text-black"     , style: { fontFamily: 'system-ui, -apple-system, sans-serif' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 129}}
            /* Title */
            , React.createElement('h1', { className: "text-3xl font-bold mb-6 text-black"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 131}}
                , data.title
            )

            /* Content Sections */
            , React.createElement('div', { className: "space-y-6", __self: this, __source: {fileName: _jsxFileName, lineNumber: 136}}
                , data.sections.map((section, index) => (
                    React.createElement('div', { key: index, className: "preview-section", __self: this, __source: {fileName: _jsxFileName, lineNumber: 138}}
                        , section.heading && (
                            React.createElement('h2', { className: "text-xl font-semibold mb-3 text-black"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 140}}
                                , section.heading
                            )
                        )
                        , React.createElement('div', {
                            className: "text-base leading-normal text-black"  ,
                            style: { lineHeight: '1.6' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 144}}

                            , section.type === 'list' ? (
                                React.createElement('ul', { className: "list-none pl-0 space-y-2"  , __self: this, __source: {fileName: _jsxFileName, lineNumber: 149}}
                                    , section.content.split('\n').filter(Boolean).map((item, i) => (
                                        React.createElement('li', { key: i, className: "before:content-['–'] before:mr-2" , __self: this, __source: {fileName: _jsxFileName, lineNumber: 151}}, item)
                                    ))
                                )
                            ) : (
                                React.createElement('p', { className: "whitespace-pre-wrap", __self: this, __source: {fileName: _jsxFileName, lineNumber: 155}}, section.content)
                            )
                        )
                    )
                ))
            )
        )
    );
};

/**
 * Creative Preset
 * Modern, gradient accents, asymmetric layout
 */
export const CreativePreset = ({ data }) => {
    return (
        React.createElement('div', { className: "max-w-[850px] mx-auto px-10 py-14 bg-gradient-to-br from-gray-50 to-gray-100 text-gray-900"       , style: { fontFamily: 'Outfit, sans-serif' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 171}}
            /* Title with gradient */
            , React.createElement('h1', { className: "text-5xl font-black mb-4 bg-gradient-to-r from-[#00ff88] to-[#00cc66] bg-clip-text text-transparent"       , __self: this, __source: {fileName: _jsxFileName, lineNumber: 173}}
                , data.title
            )

            /* Metadata with accent */
            , data.metadata && (
                React.createElement('div', { className: "flex gap-3 text-sm text-gray-600 mb-10 pb-4 border-b-2 border-[#00ff88]"       , __self: this, __source: {fileName: _jsxFileName, lineNumber: 179}}
                    , data.metadata.wordCount && React.createElement('span', { className: "px-3 py-1 bg-white rounded-full"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 180}}, data.metadata.wordCount, " words" )
                    , data.metadata.readTime && React.createElement('span', { className: "px-3 py-1 bg-white rounded-full"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 181}}, data.metadata.readTime, " min" )
                    , data.metadata.count && React.createElement('span', { className: "px-3 py-1 bg-white rounded-full"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 182}}, data.metadata.count, " items" )
                )
            )

            /* Content Sections */
            , React.createElement('div', { className: "space-y-10", __self: this, __source: {fileName: _jsxFileName, lineNumber: 187}}
                , data.sections.map((section, index) => (
                    React.createElement('div', { key: index, className: "relative pl-6 border-l-4 border-[#00ff88] preview-section"    , __self: this, __source: {fileName: _jsxFileName, lineNumber: 189}}
                        , section.heading && (
                            React.createElement('h2', { className: "text-2xl font-bold mb-4 text-gray-800"   , __self: this, __source: {fileName: _jsxFileName, lineNumber: 191}}
                                , section.heading
                            )
                        )
                        , React.createElement('div', {
                            className: "text-base leading-relaxed text-gray-700"  ,
                            style: { lineHeight: '1.7' }, __self: this, __source: {fileName: _jsxFileName, lineNumber: 195}}

                            , section.type === 'list' ? (
                                React.createElement('ul', { className: "list-none pl-0 space-y-3"  , __self: this, __source: {fileName: _jsxFileName, lineNumber: 200}}
                                    , section.content.split('\n').filter(Boolean).map((item, i) => (
                                        React.createElement('li', { key: i, className: "flex items-start gap-3"  , __self: this, __source: {fileName: _jsxFileName, lineNumber: 202}}
                                            , React.createElement('span', { className: "w-2 h-2 rounded-full bg-[#00ff88] mt-2 flex-shrink-0"     , __self: this, __source: {fileName: _jsxFileName, lineNumber: 203}})
                                            , React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 204}}, item)
                                        )
                                    ))
                                )
                            ) : (
                                React.createElement('p', { className: "whitespace-pre-wrap", __self: this, __source: {fileName: _jsxFileName, lineNumber: 209}}, section.content)
                            )
                        )
                    )
                ))
            )

            /* Footer with gradient */
            , React.createElement('div', { className: "mt-14 pt-6 border-t border-gray-300 text-sm text-gray-500 flex justify-between items-center"        , __self: this, __source: {fileName: _jsxFileName, lineNumber: 217}}
                , React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 218}}, "PDFy Document Preview"  )
                , React.createElement('span', {__self: this, __source: {fileName: _jsxFileName, lineNumber: 219}}, new Date().toLocaleDateString())
            )
        )
    );
};
