import React from 'react';
import type { PreviewData } from '../../../utils/contentTransformer';
import '../animations.css';

interface PresetProps {
    data: PreviewData;
}

/**
 * Professional Preset
 * Clean, corporate styling with Inter font
 */
export const ProfessionalPreset: React.FC<PresetProps> = ({ data }) => {
    return (
        <div className="max-w-[800px] mx-auto px-8 py-12 bg-white text-black font-sans">
            {/* Title */}
            <h1 className="text-4xl font-bold mb-2 text-gray-900" style={{ fontFamily: 'Inter, sans-serif' }}>
                {data.title}
            </h1>

            {/* Metadata */}
            {data.metadata && (
                <div className="flex gap-4 text-sm text-gray-500 mb-8 pb-4 border-b border-gray-200">
                    {data.metadata.wordCount && <span>{data.metadata.wordCount} words</span>}
                    {data.metadata.readTime && <span>• {data.metadata.readTime} min read</span>}
                    {data.metadata.count && <span>• {data.metadata.count} items</span>}
                    {data.metadata.totalQuestions && <span>• {data.metadata.totalQuestions} questions</span>}
                    {data.metadata.totalCards && <span>• {data.metadata.totalCards} cards</span>}
                </div>
            )}

            {/* Content Sections */}
            <div className="space-y-8">
                {data.sections.map((section, index) => (
                    <div key={index} className="preview-section">
                        {section.heading && (
                            <h2 className="text-2xl font-semibold mb-4 text-gray-800">
                                {section.heading}
                            </h2>
                        )}
                        <div
                            className="text-base leading-relaxed text-gray-700"
                            style={{ lineHeight: '1.75' }}
                        >
                            {section.type === 'list' ? (
                                <ul className="list-disc pl-6 space-y-2">
                                    {section.content.split('\n').filter(Boolean).map((item, i) => (
                                        <li key={i}>{item}</li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="whitespace-pre-wrap">{section.content}</p>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="mt-12 pt-6 border-t border-gray-200 text-sm text-gray-400 text-center">
                Generated by PDFy • {new Date().toLocaleDateString()}
            </div>
        </div>
    );
};

/**
 * Academic Preset
 * Serif font, formal styling, two-column layout for content
 */
export const AcademicPreset: React.FC<PresetProps> = ({ data }) => {
    return (
        <div className="max-w-[900px] mx-auto px-12 py-16 bg-white text-black" style={{ fontFamily: 'Georgia, serif' }}>
            {/* Title */}
            <h1 className="text-5xl font-bold mb-3 text-center text-gray-900">
                {data.title}
            </h1>

            {/* Metadata */}
            {data.metadata && (
                <div className="text-center text-sm text-gray-600 mb-12 pb-6 border-b-2 border-gray-300">
                    {data.metadata.wordCount && <span>{data.metadata.wordCount} words</span>}
                    {data.metadata.readTime && <span> • {data.metadata.readTime} minute read</span>}
                    {data.metadata.totalQuestions && <span> • {data.metadata.totalQuestions} questions</span>}
                </div>
            )}

            {/* Content Sections */}
            <div className="space-y-12">
                {data.sections.map((section, index) => (
                    <div key={index} className="preview-section">
                        {section.heading && (
                            <h2 className="text-3xl font-semibold mb-6 text-gray-800 border-b border-gray-300 pb-2">
                                {section.heading}
                            </h2>
                        )}
                        <div
                            className="text-lg leading-loose text-gray-800"
                            style={{ lineHeight: '2.0', textAlign: 'justify' }}
                        >
                            {section.type === 'list' ? (
                                <ul className="list-decimal pl-8 space-y-3">
                                    {section.content.split('\n').filter(Boolean).map((item, i) => (
                                        <li key={i} className="pl-2">{item}</li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="whitespace-pre-wrap indent-8">{section.content}</p>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="mt-16 pt-8 border-t-2 border-gray-300 text-center text-sm text-gray-500">
                <p>Generated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            </div>
        </div>
    );
};

/**
 * Minimal Preset
 * Ultra-clean, system fonts, narrow column
 */
export const MinimalPreset: React.FC<PresetProps> = ({ data }) => {
    return (
        <div className="max-w-[600px] mx-auto px-6 py-10 bg-white text-black" style={{ fontFamily: 'system-ui, -apple-system, sans-serif' }}>
            {/* Title */}
            <h1 className="text-3xl font-bold mb-6 text-black">
                {data.title}
            </h1>

            {/* Content Sections */}
            <div className="space-y-6">
                {data.sections.map((section, index) => (
                    <div key={index} className="preview-section">
                        {section.heading && (
                            <h2 className="text-xl font-semibold mb-3 text-black">
                                {section.heading}
                            </h2>
                        )}
                        <div
                            className="text-base leading-normal text-black"
                            style={{ lineHeight: '1.6' }}
                        >
                            {section.type === 'list' ? (
                                <ul className="list-none pl-0 space-y-2">
                                    {section.content.split('\n').filter(Boolean).map((item, i) => (
                                        <li key={i} className="before:content-['–'] before:mr-2">{item}</li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="whitespace-pre-wrap">{section.content}</p>
                            )}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

/**
 * Creative Preset
 * Modern, gradient accents, asymmetric layout
 */
export const CreativePreset: React.FC<PresetProps> = ({ data }) => {
    return (
        <div className="max-w-[850px] mx-auto px-10 py-14 bg-gradient-to-br from-gray-50 to-gray-100 text-gray-900" style={{ fontFamily: 'Outfit, sans-serif' }}>
            {/* Title with gradient */}
            <h1 className="text-5xl font-black mb-4 bg-gradient-to-r from-[#00ff88] to-[#00cc66] bg-clip-text text-transparent">
                {data.title}
            </h1>

            {/* Metadata with accent */}
            {data.metadata && (
                <div className="flex gap-3 text-sm text-gray-600 mb-10 pb-4 border-b-2 border-[#00ff88]">
                    {data.metadata.wordCount && <span className="px-3 py-1 bg-white rounded-full">{data.metadata.wordCount} words</span>}
                    {data.metadata.readTime && <span className="px-3 py-1 bg-white rounded-full">{data.metadata.readTime} min</span>}
                    {data.metadata.count && <span className="px-3 py-1 bg-white rounded-full">{data.metadata.count} items</span>}
                </div>
            )}

            {/* Content Sections */}
            <div className="space-y-10">
                {data.sections.map((section, index) => (
                    <div key={index} className="relative pl-6 border-l-4 border-[#00ff88] preview-section">
                        {section.heading && (
                            <h2 className="text-2xl font-bold mb-4 text-gray-800">
                                {section.heading}
                            </h2>
                        )}
                        <div
                            className="text-base leading-relaxed text-gray-700"
                            style={{ lineHeight: '1.7' }}
                        >
                            {section.type === 'list' ? (
                                <ul className="list-none pl-0 space-y-3">
                                    {section.content.split('\n').filter(Boolean).map((item, i) => (
                                        <li key={i} className="flex items-start gap-3">
                                            <span className="w-2 h-2 rounded-full bg-[#00ff88] mt-2 flex-shrink-0"></span>
                                            <span>{item}</span>
                                        </li>
                                    ))}
                                </ul>
                            ) : (
                                <p className="whitespace-pre-wrap">{section.content}</p>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer with gradient */}
            <div className="mt-14 pt-6 border-t border-gray-300 text-sm text-gray-500 flex justify-between items-center">
                <span>PDFy Document Preview</span>
                <span>{new Date().toLocaleDateString()}</span>
            </div>
        </div>
    );
};
